# Generated by Django 2.2.1 on 2019-05-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('storage_type', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(to='inventory.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
                ('perishable', models.BooleanField(default=True, verbose_name='perishable food')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.User')),
            ],
        ),
    ]
