# Generated by Django 2.2.1 on 2019-07-24 04:42

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190621_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='storage',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('DAIRY', 'dairy'), ('MEAT', 'meat'), ('VEGETABLES_AND_FRUITS', 'vegetables_and_fruits'), ('GRAINS', 'grains'), ('SNACKS', 'snacks'), ('DRINKS', 'drinks')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
